In [49]:
import pandas as pd
import scipy.stats
import seaborn as sns
import numpy as np
from scipy.stats import chi2

In [40]:
chi_data = pd.read_csv("data.csv")

In [41]:
chi_data.head()

Name    Age  Gender  MWP_BC  MQB_BC  MWP_AC  MQB_AC  \
0            Aarjav  16-20    Male     0.0       0     0.0       0   
1            Aashna  16-20  Female    20.0      20    90.0     200   
2     Aatman Vaidya  16-20    Male    30.0       0    70.0     900   
3           Aayushi  16-20  Female    50.0      50    95.0    1000   
4  Aayushi Sameriya  16-20  Female    70.0       0   100.0       1   

               Type   Brand  
0     Alcohol based  Dettol  
1     Alcohol based  Dettol  
2     Alcohol based    Any   
3  Anything is fine  Dettol  
4     Alcohol based  Dettol

In [32]:
# chi_data.drop(["Name","Unnamed: 0","Age","MQB_BC","MQB_AC","Type","Brand"], axis=1,inplace=True)

In [ ]:
chi_data.head()

In [59]:
def chi_square_test(variable_1, variable_2):
    independence_data_chi=pd.crosstab(chi_data[variable_1],chi_data[variable_2])
    Observed_values = independence_data_chi.values
    print("The observed Values are:\n", Observed_values)
    b = scipy.stats.chi2_contingency(independence_data_chi)
    Expected_value = b[3]
    print("\nThe expected Values are :\n", Expected_value)
    no_of_rows=len(independence_data_chi.iloc[0:2,0])
    no_of_columns=len(independence_data_chi.iloc[0,0:3])
    df=(no_of_rows-1)*(no_of_columns-1)
    print("\nDegree of Freedom: ",df)
    alpha = 0.05
    chi_square = sum([(o-e)**2./e for o,e in zip(Observed_values,Expected_value)])
    chi_square_statistic=chi_square[0]+chi_square[1]
    p_value=chi2.cdf(x=chi_square_statistic,df=df)
    print("\nP-value:",p_value)
    if p_value <= alpha:
        print("\nWe Reject Null Hypothesis, the two variables %s and %s are dependent" %(variable_1,variable_2))
    else:
        print("\nThere is no enough evidence to Reject null hypothesis, hence the two variables %s and %s are independent" %(variable_1,variable_2))

In [61]:
chi_square_test('Gender','Type')

The observed Values are:
 [[16  5 11]
 [31  7  9]]

The expected Values are :
 [[19.03797468  4.86075949  8.10126582]
 [27.96202532  7.13924051 11.89873418]]

Degree of Freedom:  2

P-value: 0.33686477201788584

There is no enough evidence to Reject null hypothesis, hence the two variables Gender and Type are independent


In [62]:
chi_square_test('Gender','Brand')

The observed Values are:
 [[ 0  0  0 20  0  2  8  2]
 [ 3  1  1 27  2  3  8  2]]

The expected Values are :
 [[ 1.21518987  0.40506329  0.40506329 19.03797468  0.81012658  2.02531646
   6.48101266  1.62025316]
 [ 1.78481013  0.59493671  0.59493671 27.96202532  1.18987342  2.97468354
   9.51898734  2.37974684]]

Degree of Freedom:  2

P-value: 0.7437757208611362

There is no enough evidence to Reject null hypothesis, hence the two variables Gender and Brand are independent


In [66]:
chi_square_test('Gender','MQB_AC')

The observed Values are:
 [[0 1 1 0 1 0 1 3 2 1 4 1 3 1 1 1 3 0 3 0 0 0 1 2 0 0 1 0 1]
 [1 0 1 1 0 1 0 5 0 1 6 1 4 0 1 0 3 1 6 1 1 1 5 3 1 1 1 1 0]]

The expected Values are :
 [[0.40506329 0.40506329 0.81012658 0.40506329 0.40506329 0.40506329
  0.40506329 3.24050633 0.81012658 0.81012658 4.05063291 0.81012658
  2.83544304 0.40506329 0.81012658 0.40506329 2.43037975 0.40506329
  3.64556962 0.40506329 0.40506329 0.40506329 2.43037975 2.02531646
  0.40506329 0.40506329 0.81012658 0.40506329 0.40506329]
 [0.59493671 0.59493671 1.18987342 0.59493671 0.59493671 0.59493671
  0.59493671 4.75949367 1.18987342 1.18987342 5.94936709 1.18987342
  4.16455696 0.59493671 1.18987342 0.59493671 3.56962025 0.59493671
  5.35443038 0.59493671 0.59493671 0.59493671 3.56962025 2.97468354
  0.59493671 0.59493671 1.18987342 0.59493671 0.59493671]]

Degree of Freedom:  2

P-value: 0.6586341598991587

There is no enough evidence to Reject null hypothesis, hence the two variables Gender and MQB_AC are independ